# Generated by Django 5.1.6 on 2025-02-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("000000", "Black"),
                            ("ffd800", "Yellow"),
                            ("ff0000", "Red"),
                            ("0090ff", "Blue"),
                            ("00b20d", "Green"),
                        ],
                        default="000000",
                        max_length=6,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[("#", "Food"), ("#", "Car"), ("#", "Bar")],
                        default="#",
                        max_length=255,
                    ),
                ),
                ("limit", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("000000", "Black"),
                            ("ffd800", "Yellow"),
                            ("ff0000", "Red"),
                            ("0090ff", "Blue"),
                            ("00b20d", "Green"),
                        ],
                        default="000000",
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
