# Generated by Django 5.1.6 on 2025-02-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                choices=[("#4", "Food"), ("#3", "Car"), ("#6", "Bar")],
                default="#",
                max_length=255,
            ),
        ),
    ]
