# Generated by Django 5.1.6 on 2025-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0003_alter_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=6),
        ),
    ]
